// app.js — all DOM rendering and wiring. Derived values come from engine.js;
// nothing computed here is stored. Keep the plain-language comments: a coding
// beginner maintains this.

import { PLANS } from "./plans.js";
import {
  getWeekComparison, round5, phaseFor, CURVES,
  parseISODate, blockStartDate
} from "./engine.js";
import {
  loadSettings, saveSettings, hasSettings,
  backupStatusText, exportToFile, parseImport
} from "./storage.js";

// ---- Small helpers ----

const $ = sel => document.querySelector(sel);

// Escape any text that comes from data before putting it in innerHTML.
function esc(s) {
  return String(s)
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const MONTHS = ["January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December"];
const WEEKDAYS = ["Sunday", "Monday", "Tuesday", "Wednesday",
  "Thursday", "Friday", "Saturday"];

// English date, e.g. "Sunday, 9 May 2027". No locale dependence.
function formatDate(dateObj) {
  return `${WEEKDAYS[dateObj.getDay()]}, ${dateObj.getDate()} ${MONTHS[dateObj.getMonth()]} ${dateObj.getFullYear()}`;
}
// Shorter form, e.g. "9 May 2027".
function formatDateShort(dateObj) {
  return `${dateObj.getDate()} ${MONTHS[dateObj.getMonth()]} ${dateObj.getFullYear()}`;
}
function weeksWord(n) { return n === 1 ? "week" : "weeks"; }

const TIER_LABEL = { beginner: "Beginner", intermediate: "Intermediate", advanced: "Advanced" };

// ---- State ----

let settings = loadSettings();
let currentTab = "now";

// ---- Backup status ----

function renderBackupStatus() {
  $("#backup-status").textContent = backupStatusText();
}

// ---- Toast (for save failures and import results) ----

let toastTimer = null;
function toast(message, warn = false) {
  const existing = $(".toast");
  if (existing) existing.remove();
  const el = document.createElement("div");
  el.className = "toast" + (warn ? " warn" : "");
  el.textContent = message;
  document.body.appendChild(el);
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => el.remove(), 3200);
}

// ============================================================
//  NOW tab
// ============================================================

function renderNow() {
  const host = $("#tab-now");

  if (!hasSettings()) {
    host.innerHTML = `
      <div class="empty">
        <h2>Set your race date</h2>
        <p>Enter your marathon date and, if you like, your current weekly volume. This tool then shows where you roughly are and how the major plans would treat this point.</p>
        <button class="btn primary" id="empty-open-settings">Set your race date</button>
      </div>`;
    $("#empty-open-settings").addEventListener("click", openSettings);
    return;
  }

  const race = parseISODate(settings.raceDate);
  const cmp = getWeekComparison(settings.raceDate, settings.weeklyVolumeKm, settings.blockWeeks);
  const wtr = cmp.weeksToRace;

  // ---- Countdown headline ----
  let headline, sub;
  if (cmp.overall === "done") {
    headline = "Race day has passed";
    sub = `Your race date was ${formatDate(race)}. Update it in Settings when the next one is set.`;
  } else if (cmp.overall === "raceweek") {
    headline = "Race week";
    sub = `Race day is ${formatDate(race)}.`;
  } else {
    headline = `<span class="countdown-num">${wtr}</span> ${weeksWord(wtr)} until race day`;
    sub = `Race day is ${formatDate(race)}.`;
  }

  let html = `
    <div class="card">
      <p class="countdown">${headline}</p>
      <p class="countdown-sub">${esc(sub)}</p>
      ${cmp.overall !== "done" ? timelineSVG(cmp, race) : ""}
    </div>`;

  // ---- Current state ----
  if (cmp.overall === "before") {
    html += basePhaseCard(cmp, race);
    html += beforePlansCard(cmp);
  } else if (cmp.overall === "active" || cmp.overall === "raceweek") {
    html += activeComparisonCard(cmp);
    html += yourPositionCard(cmp);
  } else if (cmp.overall === "done") {
    html += `<div class="card"><p class="lead">Set a new race date to see the comparison again.</p></div>`;
  }

  // ---- Disclaimer (always, when settings exist) ----
  html += `<p class="disclaimer">Approximate shapes, not the real schedules. The numbers are generated by this tool and snapped to the nearest 5 km. See each plan's source for the actual schedule.</p>`;

  // ---- Edit settings ----
  html += `<div style="margin-top:1rem"><button class="btn" id="now-open-settings">Edit settings</button></div>`;

  host.innerHTML = html;
  $("#now-open-settings").addEventListener("click", openSettings);
}

// Base-phase card: one recurring state, warm and not-a-beginner. No weekly cards.
function basePhaseCard(cmp, race) {
  const userStart = blockStartDate(race, cmp.userBlockWeeks);
  const startsIn = cmp.userBlockStartsInWeeks;
  let startLine;
  if (startsIn > 0) {
    startLine = `Your ${cmp.userBlockWeeks} week block would begin in about ${startsIn} ${weeksWord(startsIn)}, around ${formatDateShort(userStart)}.`;
  } else {
    startLine = `Your ${cmp.userBlockWeeks} week block has begun. The published 18 week plans start a little later.`;
  }
  return `
    <div class="card">
      <p class="section-h">Right now</p>
      <p class="lead" style="color:var(--ink)">You are outside the structured block. Keep consistent easy running with one long run a week, and stay healthy. There is no rush to ramp up yet.</p>
      <p class="plan-detail" style="margin-top:0.7rem">${esc(startLine)}</p>
    </div>`;
}

// In base phase, plans have not started. Show a compact "begins in" row each,
// with the one-line philosophy. Not weekly cards, just where each plan sits.
function beforePlansCard(cmp) {
  const rows = cmp.plans.map(r => {
    const inWks = r.startsInWeeks;
    return `
      <div class="plan-card">
        <div class="plan-card-head">
          <span class="plan-name">${esc(r.name)}</span>
          <span class="tier-badge">${esc(TIER_LABEL[r.tier] || r.tier)}</span>
        </div>
        <p class="plan-before"><span class="starts">Begins in about ${inWks} ${weeksWord(inWks)}</span></p>
        <p class="plan-detail">${esc(r.philosophy)}</p>
        <p class="plan-source"><a href="${esc(r.source.url)}" target="_blank" rel="noopener noreferrer">${esc(r.source.label)}</a></p>
      </div>`;
  }).join("");
  return `
    <div class="card">
      <p class="section-h">The plans, not started yet</p>
      <div class="plan-grid">${rows}</div>
    </div>`;
}

// Active state: a card per plan at this point in time.
function activeComparisonCard(cmp) {
  const active = cmp.plans.filter(r => r.state === "active");
  const rows = active.map(r => `
    <div class="plan-card">
      <div class="plan-card-head">
        <span class="plan-name">${esc(r.name)}</span>
        <span class="tier-badge">${esc(TIER_LABEL[r.tier] || r.tier)}</span>
      </div>
      <p class="plan-phase">${esc(r.phase)} &middot; ${esc(r.weekLabel)}</p>
      <p class="plan-km">~${r.approxKm} km<small> per week</small></p>
      <p class="plan-detail"><strong>Signature:</strong> ${esc(r.signatureWorkout)}</p>
      <p class="plan-meta">Guided by ${esc(paceApproachLabel(r.paceApproach))}</p>
      <p class="plan-source"><a href="${esc(r.source.url)}" target="_blank" rel="noopener noreferrer">${esc(r.source.label)}</a></p>
    </div>`).join("");
  return `
    <div class="card">
      <p class="section-h">Where each plan sits right now</p>
      <div class="plan-grid active-grid">${rows}</div>
    </div>`;
}

function paceApproachLabel(a) {
  return { mileage: "weekly mileage", pace: "pace targets", effort: "effort" }[a] || a;
}

// Your position: user's volume against the active spread, with an SVG ladder.
function yourPositionCard(cmp) {
  const pos = cmp.myPosition;
  if (!settings.weeklyVolumeKm) {
    return `
      <div class="card">
        <p class="section-h">Your position</p>
        <p class="lead">Add your current weekly volume in Settings to mark where you sit against the plans.</p>
      </div>`;
  }
  if (!pos) {
    return `
      <div class="card">
        <p class="section-h">Your position</p>
        <p class="lead">No plan is active at this point, so there is nothing to compare against yet.</p>
      </div>`;
  }
  const my = pos.myKm;
  let line;
  if (pos.above.length && pos.below.length) {
    line = `At about <span class="hi">${my} km</span> per week you are at or above ${listNames(pos.above)}, and below ${listNames(pos.below)}.`;
  } else if (pos.above.length && !pos.below.length) {
    line = `At about <span class="hi">${my} km</span> per week you are at or above every plan's mark for this point.`;
  } else {
    line = `At about <span class="hi">${my} km</span> per week you are below every plan's mark for this point.`;
  }
  return `
    <div class="card">
      <p class="section-h">Your position</p>
      <p class="position-line">${line}</p>
      ${ladderSVG(cmp)}
    </div>`;
}

function listNames(names) {
  if (names.length === 1) return esc(names[0]);
  if (names.length === 2) return `${esc(names[0])} and ${esc(names[1])}`;
  return names.slice(0, -1).map(esc).join(", ") + ", and " + esc(names[names.length - 1]);
}

// ---- Timeline: an SVG bar (now to race, block region shaded) plus an HTML
// legend below. The labels live in HTML, not SVG text, so they stay legible at
// mobile width where a wide viewBox would shrink SVG text too far to read. ----
function timelineSVG(cmp, race) {
  const W = 680, H = 26, padX = 12;
  const innerW = W - padX * 2;
  const wtr = Math.max(cmp.weeksToRace, 0);
  const trackY = 13;

  // Block region is the last `userBlockWeeks` before the race. Show a distinct
  // block-start marker only while the block is still ahead; once it is underway
  // (block longer than the time remaining) the whole track is the block.
  const span = Math.max(wtr, 1);
  const blockAhead = cmp.userBlockWeeks < span;
  const blockStartWeeksOut = Math.min(cmp.userBlockWeeks, span);
  const blockX = padX + innerW * (1 - blockStartWeeksOut / span);

  const raceStr = formatDateShort(race);
  const blockStr = formatDateShort(blockStartDate(race, cmp.userBlockWeeks));

  const blockDot = blockAhead
    ? `<circle cx="${blockX.toFixed(1)}" cy="${trackY}" r="5" fill="var(--sage-bright-deep)"/>`
    : "";

  const svg = `
    <svg class="timeline" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none" role="img"
         aria-label="Timeline from now to race day, with your training block shaded.">
      <line x1="${padX}" y1="${trackY}" x2="${W - padX}" y2="${trackY}"
            stroke="var(--track)" stroke-width="6" stroke-linecap="round"/>
      <line x1="${blockX.toFixed(1)}" y1="${trackY}" x2="${W - padX}" y2="${trackY}"
            stroke="var(--sage-tint)" stroke-width="6" stroke-linecap="round"/>
      <circle cx="${padX}" cy="${trackY}" r="6" fill="var(--sage)"/>
      ${blockDot}
      <circle cx="${W - padX}" cy="${trackY}" r="6" fill="var(--sage-deep)"/>
    </svg>`;

  const blockLegend = blockAhead
    ? `<span><span class="dot" style="background:var(--sage-bright-deep)"></span>Block start, ${esc(blockStr)}</span>`
    : `<span><span class="dot" style="background:var(--sage-bright-deep)"></span>Your block is underway</span>`;

  return `${svg}
    <div class="timeline-legend">
      <span><span class="dot" style="background:var(--sage)"></span>Now</span>
      ${blockLegend}
      <span><span class="dot" style="background:var(--sage-deep)"></span>Race day, ${esc(raceStr)}</span>
    </div>`;
}

// ---- Volume bars: one horizontal bar per plan plus a "You" bar, sorted low to
// high, so the spread and where you sit in it read at a glance. Plain HTML and
// CSS bars (the design system's progress-track idiom) stay legible at any width,
// unlike SVG text in a wide viewBox. ----
function ladderSVG(cmp) {
  const active = cmp.plans.filter(r => r.state === "active" && r.approxKm);
  if (!active.length) return "";
  const my = cmp.myPosition.myKm;

  // Build the rows, insert "You", and sort ascending so you sit in the spread.
  const rows = active.map(r => ({ label: r.short || r.name, km: r.approxKm, you: false }));
  rows.push({ label: "You", km: my, you: true });
  rows.sort((a, b) => a.km - b.km || (a.you ? 1 : -1));

  const maxKm = Math.max(...rows.map(r => r.km), 1);
  const bars = rows.map(r => {
    const pct = Math.round((r.km / maxKm) * 100);
    return `
      <div class="vol-row${r.you ? " you" : ""}">
        <span class="vol-name">${esc(r.label)}</span>
        <span class="vol-track"><span class="vol-fill" style="width:${pct}%"></span></span>
        <span class="vol-val">~${r.km} km</span>
      </div>`;
  }).join("");

  return `<div class="vol-bars" role="img"
      aria-label="Your weekly volume compared with each plan's approximate volume for this point.">${bars}</div>`;
}

// ============================================================
//  PLANS tab (reference content)
// ============================================================

function renderPlans() {
  const host = $("#tab-plans");
  const cards = Object.values(PLANS).map(p => {
    const peak = round5(p.peakVolume);
    const longRun = round5(p.longRunPeakKm);
    return `
      <div class="plan-card">
        <div class="plan-card-head">
          <span class="plan-name">${esc(p.name)}</span>
          <span class="tier-badge">${esc(TIER_LABEL[p.tier] || p.tier)}</span>
        </div>
        <p class="plan-detail">${esc(p.philosophy)}</p>
        <p class="plan-detail"><strong>Signature:</strong> ${esc(p.signatureWorkout)}</p>
        <p class="plan-detail"><strong>Best for:</strong> ${esc(p.bestFor)}</p>
        <p class="plan-meta">Peaks around ${peak} km per week, roughly ${p.peakWeekOut} ${weeksWord(p.peakWeekOut)} out. Longest run about ${longRun} km. Guided by ${esc(paceApproachLabel(p.paceApproach))}. ${p.blockWeeks} week block.</p>
        <p class="plan-source"><a href="${esc(p.source.url)}" target="_blank" rel="noopener noreferrer">${esc(p.source.label)}</a></p>
      </div>`;
  }).join("");
  host.innerHTML = `
    <div class="card">
      <p class="section-h">The plans compared</p>
      <p class="lead" style="margin-bottom:0.9rem">Five well known marathon builds, low to high volume. These are characterizations to help you choose one to follow, not the schedules themselves.</p>
      <div class="plan-grid">${cards}</div>
    </div>
    <p class="disclaimer">Peak and long-run figures are approximate, widely known facts, snapped to the nearest 5 km. For the real week by week plan, follow the source link.</p>`;
}

// ============================================================
//  PRINCIPLES tab (static reference, §8)
// ============================================================

const PRINCIPLES = [
  { title: "Easy runs carry most of the load",
    body: "About 80 percent of weekly running is easy, about 20 percent is hard. Most plans differ mainly in how they spend that 20 percent." },
  { title: "Build volume gradually",
    body: "Weekly volume grows by roughly 10 percent per week at most. A jump larger than that is where injuries tend to start." },
  { title: "The long run is a share, not a race",
    body: "The long run is a portion of the week's volume, run easy. Its job is time on feet, not a hard effort of its own." },
  { title: "Strength work, about twice a week",
    body: "Two short strength sessions a week support the running and help hold form as fatigue builds." },
  { title: "Taper for 2 to 3 weeks",
    body: "Volume comes down over the final 2 to 3 weeks so you arrive fresh. Sharpness is kept, fatigue is shed." }
];

function renderPrinciples() {
  const host = $("#tab-principles");
  const items = PRINCIPLES.map(p => `
    <div class="principle">
      <p class="principle-title">${esc(p.title)}</p>
      <p class="principle-body">${esc(p.body)}</p>
    </div>`).join("");
  host.innerHTML = `
    <div class="card">
      <p class="section-h">Stable training principles</p>
      <p class="lead" style="margin-bottom:0.6rem">These hold across plans and across the whole build, so they live here once rather than on every card.</p>
      ${items}
    </div>
    <div class="card">
      <p class="section-h">A note on pace</p>
      <p class="lead">A tune-up race a few months out is a useful fitness check and a fair predictor of realistic marathon pace. Turning "run long runs easy" into "run them at a set pace" needs a goal pace input. That is planned for a later version and is not part of this one.</p>
    </div>`;
}

// ============================================================
//  Tabs
// ============================================================

function switchTab(name) {
  currentTab = name;
  document.querySelectorAll(".tab").forEach(t => {
    t.setAttribute("aria-selected", String(t.dataset.tab === name));
  });
  $("#tab-now").hidden = name !== "now";
  $("#tab-plans").hidden = name !== "plans";
  $("#tab-principles").hidden = name !== "principles";
  if (name === "now") renderNow();
  else if (name === "plans") renderPlans();
  else if (name === "principles") renderPrinciples();
}

// ============================================================
//  Settings panel
// ============================================================

function openSettings() {
  // Fill the form from current settings each time it opens.
  $("#race-date").value = settings.raceDate || "";
  $("#weekly-volume").value = settings.weeklyVolumeKm ?? "";
  $("#block-weeks").value = String(settings.blockWeeks || 18);
  $("#settings-panel").classList.add("open");
  $("#settings-panel").setAttribute("aria-hidden", "false");
  $("#panel-backdrop").classList.add("open");
}

function closeSettings() {
  $("#settings-panel").classList.remove("open");
  $("#settings-panel").setAttribute("aria-hidden", "true");
  $("#panel-backdrop").classList.remove("open");
}

// Read the form, save, and re-render. Autosave on every change (no save button).
function applySettingsFromForm() {
  const raceDate = $("#race-date").value || "";
  const volRaw = $("#weekly-volume").value;
  const vol = volRaw === "" ? null : Math.max(0, Math.round(Number(volRaw)));
  const blockWeeks = Number($("#block-weeks").value) || 18;

  settings = {
    ...settings,
    raceDate,
    weeklyVolumeKm: Number.isFinite(vol) ? vol : null,
    blockWeeks
  };
  const ok = saveSettings(settings);
  if (!ok) {
    toast("Could not save to this browser. Your change may not be kept.", true);
  }
  if (currentTab === "now") renderNow();
}

// ============================================================
//  Export / Import
// ============================================================

function doExport() {
  if (!hasSettings()) {
    toast("Set your race date first, then export.");
    return;
  }
  exportToFile(settings);
  renderBackupStatus();
  toast("Settings exported.");
}

function doImport(file) {
  const reader = new FileReader();
  reader.onload = () => {
    try {
      const imported = parseImport(String(reader.result));
      settings = imported;
      const ok = saveSettings(settings);
      if (!ok) { toast("Imported, but could not save to this browser.", true); }
      else { toast("Settings imported."); }
      switchTab("now");
    } catch (e) {
      toast(e.message || "Could not read that file.", true);
    }
  };
  reader.onerror = () => toast("Could not read that file.", true);
  reader.readAsText(file);
}

// ============================================================
//  Wiring
// ============================================================

function wire() {
  // Tabs
  document.querySelectorAll(".tab").forEach(t => {
    t.addEventListener("click", () => switchTab(t.dataset.tab));
  });

  // Settings panel
  $("#settings-done").addEventListener("click", closeSettings);
  $("#panel-backdrop").addEventListener("click", closeSettings);
  $("#settings-form").addEventListener("change", applySettingsFromForm);
  $("#weekly-volume").addEventListener("input", applySettingsFromForm);

  // About modal
  $("#about-btn").addEventListener("click", () => { $("#about-modal").hidden = false; });
  $("#about-close").addEventListener("click", () => { $("#about-modal").hidden = true; });
  $("#about-modal").addEventListener("click", e => {
    if (e.target === $("#about-modal")) $("#about-modal").hidden = true;
  });

  // Export / Import
  $("#export-btn").addEventListener("click", doExport);
  $("#import-btn").addEventListener("click", () => $("#import-file").click());
  $("#import-file").addEventListener("change", e => {
    const file = e.target.files && e.target.files[0];
    if (file) doImport(file);
    e.target.value = "";   // allow re-importing the same file
  });

  // Close panels / modal on Escape
  document.addEventListener("keydown", e => {
    if (e.key === "Escape") {
      closeSettings();
      $("#about-modal").hidden = true;
    }
  });
}

// ---- Boot ----
renderBackupStatus();
wire();
switchTab("now");
